### ISSUE TITLE
Support library dependency conflict

### ISSUE THREAD

**Issue by ghorkov32** [aviadmini/quickimagepick#5]
Hi, i'm having an issue with the default Floating Action Button. I'm using the default that comes with the library com.android.support:appcompat-v7:23.4.0.
It happens everytime i add the triggerResult = QiPick.in(getActivity()).fromGallery(); sentence to the main app.  

> `0-04 20:11:18.050 6399-6399/com.PuszkiApps.ivan.myapp E/AndroidRuntime: FATAL EXCEPTION: main
>                                                                             Process: com.PuszkiApps.ivan.myapp, PID: 6399
>                                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{com.PuszkiApps.ivan.myapp/com.PuszkiApps.ivan.myapp.MainActivity}: android.view.InflateException: Binary XML file line #11: Binary XML file line #26: Error inflating class android.support.design.widget.FloatingActionButton
>                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
>                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
>                                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java)
>                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
>                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
>                                                                                 at android.os.Looper.loop(Looper.java:148)
>                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417)
>                                                                                 at java.lang.reflect.Method.invoke(Native Method)
>                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
>                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
>                                                                              Caused by: android.view.InflateException: Binary XML file line #11: Binary XML file line #26: Error inflating class android.support.design.widget.FloatingActionButton
>                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
>                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
>                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
>                                                                                 at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284)
>                                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
>                                                                                 at com.PuszkiApps.ivan.myapp.MainActivity.onCreate(MainActivity.java:104)
>                                                                                 at android.app.Activity.performCreate(Activity.java:6237)
>                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
>                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
>                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
>                                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java) 
>                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
>                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
>                                                                                 at android.os.Looper.loop(Looper.java:148) 
>                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417) 
>                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
>                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
>                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
>                                                                              Caused by: android.view.InflateException: Binary XML file line #26: Error inflating class android.support.design.widget.FloatingActionButton
>                                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:645)
>                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764)
>                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704)
>                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:835)
>                                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
>                                                                                 at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971)
>                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:831)
>                                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798)
>                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
>                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
>                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
>                                                                                 at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
>                                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
>                                                                                 at com.PuszkiApps.ivan.myapp.MainActivity.onCreate(MainActivity.java:104) 
>                                                                                 at android.app.Activity.performCreate(Activity.java:6237) 
>                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
>                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
>                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
>                                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java) 
>                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
>                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
>                                                                                 at android.os.Looper.loop(Looper.java:148) 
>                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417) 
>                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
>                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
>                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
>                                                                              Caused by: java.lang.reflect.InvocationTargetException
>                                                                                 at java.lang.reflect.Constructor.newInstance(Native Method)
>                                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:619)
>                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
>                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
>                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
>                                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
>                                                                                 at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971) 
>                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:831) 
>                                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
>                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
>                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
>                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
>                                                                                 at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
>                                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
>                                                                                 at com.PuszkiApps.ivan.myapp.MainActivity.onCreate(MainActivity.java:104) 
>                                                                                 at android.app.Activity.performCreate(Activity.java:6237) 
>                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
>                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
>                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
>                                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java) 
>                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
>                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
>                                                                                 at android.os.Looper.loop(Looper.java:148) 
>                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417) 
>                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
>                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
>                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
>                                                                              Caused by: java.lang.NoSuchMethodError: No direct method <init>(Landroid/widget/ImageView;Landroid/support/v7/widget/AppCompatDrawableManager;)V in class Landroid/support/v7/widget/AppCompatImageHelper; or its super classes (declaration of 'android.support.v7.widget.AppCompatImageHelper' appears in /data/data/com.PuszkiApps.ivan.myapp/files/instant-run/dex/slice-com.android.support-appcompat-v7-24.2.1_c10241a730b84e1100812061f17ddbc3ef084fea-classes.dex)
>                                                                                 at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:170)
>                                                                                 at android.support.design.widget.FloatingActionButton.<init>(FloatingActionButton.java:147)
>                                                                                 at java.lang.reflect.Constructor.newInstance(Native Method) 
>                                                                                 at android.view.LayoutInflater.createView(LayoutInflater.java:619) 
>                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:764) 
>                                                                                 at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:704) 
>                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:835) 
>                                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
>                                                                                 at android.view.LayoutInflater.parseInclude(LayoutInflater.java:971) 
>                                                                                 at android.view.LayoutInflater.rInflate(LayoutInflater.java:831) 
>                                                                                 at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:798) 
>                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
>                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
>                                                                                 at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
>                                                                                 at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:284) 
>                                                                                 at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140) 
>                                                                                 at com.PuszkiApps.ivan.myapp.MainActivity.onCreate(MainActivity.java:104) 
>                                                                                 at android.app.Activity.performCreate(Activity.java:6237) 
>                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107) 
>                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369) 
>                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
>                                                                                 at android.app.ActivityThread.-wrap11(ActivityThread.java) 
>                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344) 
>                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
>                                                                                 at android.os.Looper.loop(Looper.java:148) 
>                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5417) 
>                                                                                 at java.lang.reflect.Method.invoke(Native Method) 
>                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
>                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) `

Thanks in advance! 😄

**Comment by ghorkov32** [comment]
Solved, i had to update my build.gradle file using the build tools and android libraries version in one of your library build files. Sorry i opened an issue, i'm new on android and i've spent 4 hours trying to figure this out, i was about to give up 😆

**Comment by aviadmini** [comment]
Glad you solved it. I'll include a note in documentation on how to prevent library conflicts
