### ISSUE TITLE
Taking with camera always get CANCEL flag

### ISSUE THREAD

**Issue by aemxn** [aviadmini/quickimagepick#7]
As per title, I always get CANCELED flag in the onActivityResult when taking photo with camera, eventhough permission is already set.

Any idea why?

Additional info, debugging the `outDir.canWrite` also returns false.

> openFileChooserDialog: /storage/emulated/0/Pictures/MyDirectory, **can write: false**

I'm using Nexus 5X with Android 7.0.1

**Comment by aviadmini** [comment]
Maybe you don't have write permission to the specified folder. Are you able to write to it manually (not using the lib) ?

**Comment by aemxn** [comment]
You're right. Folder have to exist in the external storage in order for the app to write. Can this process be done inside `.withCameraPicsDirectory()` instead of manually checking for its existence?

**Comment by aviadmini** [comment]
Yes, I think I'm going to add it in the next release

**Comment by aviadmini** [comment]
Should be good with c4320ef
It attempts to create the specified directory for camera pics if it doesn't exist
