### ISSUE TITLE
problem with multiply select

### ISSUE THREAD

**Issue by akshaylamba** [aviadmini/quickimagepick#8]
in Multiple select ...

How Do I get the Uri to Convert to File ...I Tried The Below code But it returns size of the file as Zero...

for(int i=0;i<pImageUris.size();i++) {

    File f = new File(pImageUris.get(i).getPath());

    final long size = f.length();

}

Or Let me know How Do I Return the pImageURI List to the OnactivityResult...

**Comment by aviadmini** [comment]
Please take a look at what [Uri](https://developer.android.com/reference/android/net/Uri.html) is and undestand that it is not always referencing a file. And even if it  it does reference a file it doesn't necessarily have `file:///` schema that can be parsed with `Uri.getPath()`

You can obtain an `InputStream` using `ContentResolver.openInputStream(Uri)`. Take a look at [this method](https://github.com/aviadmini/quickimagepick/blob/master/library/src/main/java/com/aviadmini/quickimagepick/UriUtils.java#L82) as an example.
